language: haskell

ghc: 7.8.2

install:
  - cabal update
  - cabal install alex happy yesod-bin --max-backjumps=-1 --reorder-goals
  - cabal install --only-dependencies --enable-tests

script:
  - yesod test

notifications:
  email: false
