language: haskell

ghc: 7.8

addons:
  postgresql: "9.3"

install:
  - mv cabal.config{,.bak}
  - cabal install alex happy yesod-bin --max-backjumps=-1 --reorder-goals
  - mv cabal.config{.bak,}

before_script:
  - ./bin/setup

script:
  - GITHUB_OAUTH_CLIENT_ID=x GITHUB_OAUTH_CLIENT_SECRET=x yesod test

notifications:
  email: false

branches:
  only:
    - master
