language: haskell

ghc: 7.8.2

install:
  - cabal update
  - cabal install cabal-install
  - cabal install alex happy yesod-bin
  - cabal install --only-dependencies --enable-tests

script:
  - yesod test

notifications:
  email: false
