language: haskell

ghc: 7.8

addons:
  postgresql: "9.3"

install:
  - cabal install alex happy yesod-bin --max-backjumps=-1 --reorder-goals

before_script:
  - ./bin/setup

script:
  - LEARN_OAUTH_CLIENT_ID=x LEARN_OAUTH_CLIENT_SECRET=x yesod test

notifications:
  email: false

branches:
  only:
    - master
