language: sh

addons:
  postgresql: "9.3"

env:
  global:
    - HALCYON_CABAL_UPDATE=1
    - GITHUB_OAUTH_CLIENT_ID=x
    - GITHUB_OAUTH_CLIENT_SECRET=x
    - secure: CIZIU8utnhZ9aT+vdvRl2dWVExSL0N9ajpyg/eh4NfSHBS8DmQTX5OMutzo3dpLrauZrT8ZT4AMDu4A1XM2XZg+R5Oz6eT5FyR1Vh2v35L5USLyQaMibIPhdPeppOXr1Fosmv23/MZNaADqpT7Rxk1CjvxqK6/Itg8sy3GodkA4=
    - secure: M1HfgGKfWPZxT/QOmZyziRm7Bq40ibkDbPHyl3+hdGUB9gsprw0fSxsJJkgG8qE55U3eIk+obPVSRQdbtv8klRlWgBwm7RIw2kYEz91C0usBf0xm7DoC6c5rikdUS7MAbBHOKcMLuGD9QXBByeEVl7/jnl3BsSj2Rt4IBZ+0ltU=
    - secure: ad468nMN2y4qtBHS6hDCKyRf57elMPgkUkcTCXB5BM3AZoXGMJugGuEsJgge1QPV+Ex3F6TXMGPWe05m9HpiB7kngJbDmyueghYBsFAvR9ftf63Fg6tGMc1qGCC6SCs0l5xt3wb9ZfFMn5rmJ08rby2TASsn/L7dMxGsKL4OV/4=

install:
  - ./bin/setup-db
  - ./bin/halcyon-build
  - /app/halcyon/halcyon paths > halcyon-env

script:
  - . halcyon-env && yesod test

notifications:
  email: false
  slack:
    secure: A+eCONhbofvAmdVTqJvsw8j8PLzSVVqNxsxmInVMscEUjjXXjEuFxngnBPXf2p0X+Qx+TvU/tgM2ukXeQ5nhELH3qxYN0Rl5uE2fjwBw1w0WyStVvVx1h1/ERgN8uftDVfhLo4qszAJxsfvV90Etd1EXqnulsm7Y+iIyRyDqMtk=

branches:
  only:
    - master
