resolver: lts-2.9

packages:
- '.'

extra-deps:
- esqueleto-2.1.2.2
- fast-logger-2.3.1
- heroku-0.1.2.2
- heroku-persistent-0.1.0
- hspec-expectations-lifted-0.5.0
- hspec-webdriver-1.1.0
- http-common-0.8.2.0
- http-streams-0.8.3.3
- io-streams-1.3.2.0
- load-env-0.1.1
- openssl-streams-1.2.1.0
- persistent-2.1.2
- persistent-postgresql-2.1.3
- persistent-template-2.1.1
- shakespeare-text-1.1.0
- smtp-mail-0.1.4.5
- stripe-core-2.0.2
- stripe-haskell-0.1.3.0
- stripe-http-streams-2.0.2
- wai-app-static-3.0.0.6
- warp-3.0.10.1
- yesod-static-1.4.0.4
