resolver: lts-5.0

packages:
- '.'

extra-deps:
- heroku-0.1.2.2
- heroku-persistent-0.1.0
- hspec-expectations-lifted-0.5.0
- load-env-0.1.1
- shakespeare-text-1.1.0
- stripe-haskell-0.1.4.3
- yesod-newsfeed-1.4.0.1
- yesod-test-1.4.3.1
