Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: "thoughtbot, inc. 2014"
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  approot: "https://carnival-staging.herokuapp.com"
  <<: *defaults

Production:
  approot: "https://carnival.thoughtbot.com"
  <<: *defaults
